// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edgobyhdagdisptodzrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkZ29ieWhkYWdkaXNwdG9kenJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mjk3MTgsImV4cCI6MjA3MzAwNTcxOH0.Xx9IElLThe_6q6J4xNMUmME5_oKGG-Gfb4Mq9Ihv5_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});